remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

base_url: https://cheiily.github.io/FGC_Scoreboard_filegen/

title: Simple Scoreboard Controller
show_downloads: true
has_nav: true
