module pl.cheily.filegen {
    requires javafx.controls;
    requires javafx.fxml;
    requires ini4j;
    requires com.opencsv;
    requires jdk.httpserver;
    requires org.json;
    requires Java.WebSocket;
    requires java.desktop;
    requires org.slf4j;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;
    requires org.controlsfx.controls;
    requires net.harawata.appdirs;
    requires java.logging;

    opens pl.cheily.filegen to javafx.fxml;
    exports pl.cheily.filegen;
    exports pl.cheily.filegen.Utils;
    opens pl.cheily.filegen.Utils to javafx.fxml;
    exports pl.cheily.filegen.UI;
    opens pl.cheily.filegen.UI to javafx.fxml;
    exports pl.cheily.filegen.LocalData;
    opens pl.cheily.filegen.LocalData to javafx.fxml;
    exports pl.cheily.filegen.LocalData.FileManagement.Meta;
    opens pl.cheily.filegen.LocalData.FileManagement.Meta to javafx.fxml;
    exports pl.cheily.filegen.LocalData.FileManagement.Output.Formatting;
    opens pl.cheily.filegen.LocalData.FileManagement.Output.Formatting to javafx.fxml;
    exports pl.cheily.filegen.LocalData.FileManagement.Output.Writing;
    opens pl.cheily.filegen.LocalData.FileManagement.Output.Writing to javafx.fxml;
    exports pl.cheily.filegen.LocalData.FileManagement.Meta.Match;
    exports pl.cheily.filegen.Notifications;
    opens pl.cheily.filegen.Notifications to javafx.fxml;
    exports pl.cheily.filegen.ResourceModules;
    opens pl.cheily.filegen.ResourceModules to javafx.fxml;
    exports pl.cheily.filegen.ResourceModules.Events;
    exports pl.cheily.filegen.ResourceModules.Plugins.SPI;
    opens pl.cheily.filegen.ResourceModules.Plugins.SPI;
    exports pl.cheily.filegen.ResourceModules.Plugins;
    exports pl.cheily.filegen.ResourceModules.Validation;
    opens pl.cheily.filegen.ResourceModules.Validation to javafx.fxml;
    exports pl.cheily.filegen.ResourceModules.Validation.Factories;
    opens pl.cheily.filegen.ResourceModules.Validation.Factories to javafx.fxml;
}